### ISSUE TITLE
Shell script linux uninstall Alfresco

### ISSUE THREAD

**Issue by jrbrasil** [loftuxab/alfresco-ubuntu-install#134]
Hi,
Does anyone have the script to uninstall the fresco, via linux shell script?
With best regards,

**Comment by chris001** [comment]
A quick web search gives these linux uninstall instructions:
https://docs.alfresco.com/5.1/tasks/uninstall-alfresco.html

**Comment by jrbrasil** [comment]
Hi Chris Coleman,
You do not have the uninstall binary in the /opt/alfresco directory
See below:

root @ servertwtech: / opt / alfresco # l
total 52K
drwxr-xr-x 6 alfresco alfresco 4.0K Feb 8 2019 solr6
drwxr-xr-x 4 alfresco alfresco 4.0K Aug 30 11:15 modules
drwxr-xr-x 2 alfresco alfresco 4.0K Aug 30 11:16 bin
drwxr-xr-x 7 alfresco alfresco 4.0K Aug 31 02:00 alf_data
-rwxr-xr-x 1 alfresco alfresco 3.6K Oct 2 17:50 alfresco-service.sh
drwxr-xr-x 2 www-data root 4.0K Nov 25 15:35 www
drwxr-xr-x 11 alfresco alfresco 4.0K Dec 6 11:02 tomcat
drwxr-xr-x 3 alfresco alfresco 4.0K Dec 30 20:00 scripts
drwxr-xr-x 6 alfresco alfresco 4.0K Jan 17 14:09 addons
-rw-r - r-- 1 alfresco alfresco 5 Jan 23 13:50 tomcat.pid
drwxr-xr-x 5 alfresco alfresco 12K Jan 25 03:00 logs

Alfresco version: Community - 6.1.1 (r9d03d2fd-b168)
Installed via alfinstall.sh script
What is the procedure to uninstall, without the uninstall?
With best regards,

**Comment by loftux** [comment]
Just remove the directory /opt/alfresco
sudo rm -r /opt/alfresco

For all the other dependencies installed with apt-get, just do the same but with uninstall. Search the script. But you can leave them since they most likely will not do any harm unless you really want a clean install. But then I recommend that you just reinstall Ubuntu Server from scratch, it is not that complicated.

So not sure what you did that you need this removed (I've seen the emails you have sent as well). But there are no uninstall script, never had a reason to uninstall. Mostly running on virtual servers, old servers get scrapped when needed, use a new fresh virtual server.

**Comment by jrbrasil** [comment]
Hi Peter Löfgren,
I need a clean installation.
Because I want to install the Community version - 5.2.0 (re21f2be5-b22).
alfresco-community-installer-201707-linux-x64.bin
Only in this version, which works PDF Toolkit - version 1.2.
In version 6.1 of Alfresco, it does not work.
I even posted on github to find out about this project.
https://github.com/OrderOfTheBee/alfresco-pdf-toolkit/issues
However, so far I have had no answer.
Can you tell me about it?
I need to remove it, since Alfresco is installed on my notebook.
I use dual boot - Windows 10 / Ubuntu Linux.
With best regards,

**Comment by loftux** [comment]
Remove /opt/alfresco as told. Should be fine.
And you can purge libreoffice if needed. Google will tell you how.
