### ISSUE TITLE
Ubuntu moving from upstart to systemd (after 14.04)

### ISSUE THREAD

**Issue by loftux** [loftuxab/alfresco-ubuntu-install#16]
Ubuntu will in future releases use systemd instead of upstart.
- Create systemd script

**Comment by housni** [comment]
This should work for Systemd:

    # Copy to /etc/systemd/system/alfresco.service
    # Then:
    #     sudo systemctl enable alfresco.service
    #     sudo systemctl daemon-reload
    #     sudo systemctl restart alfresco.service

    [Unit]
    Description=Start Alfresco Community 5 service

    [Service]
    Type=forking
    ExecStart=/bin/sh -c "/opt/alfresco/tomcat/bin/startup.sh"
    ExecStop=/bin/sh -c "/opt/alfresco/tomcat/bin/shutdown.sh"
    Restart=always

    [Install]
    WantedBy=multi-user.target

**Comment by loftux** [comment]
Thanks @housni,
We also need a way to run it as user "alfresco", and to set JAVA_OPTS is currently done with the upstart script. Maybe just a simple wrapper script instead of calling startups.sh/shutdown.sh directly is enough.

**Comment by housni** [comment]
This isn't tested, but it should work:

    # Copy to /etc/systemd/system/alfresco.service
    # Then:
    #     sudo systemctl enable alfresco.service
    #     sudo systemctl daemon-reload
    #     sudo systemctl restart alfresco.service

    [Unit]
    Description=Start Alfresco Community 5 service

    [Service]
    Type=forking
    ExecStart=/bin/sh -c "/opt/alfresco/tomcat/bin/startup.sh"
    ExecStop=/bin/sh -c "/opt/alfresco/tomcat/bin/shutdown.sh"
    Restart=always
    User=alfresco

    [Install]
    WantedBy=multi-user.target

That will start as the 'alfresco' user.
As for the JAVA_OPTS, we can probably do it like this: https://wolfpaulus.com/journal/software/tomcat-jessie/

**Comment by housni** [comment]
FYI, I tried this on 16.04 and it works but without using the `User=alfresco` line. Doing that gave me permission issues when writing log files.

I haven't looked too deep into this but I think you may be handling the user in your startup script so doing that in SystemD seems to be somehow messing with it.

**Comment by housni** [comment]
Scratch my last comment. We do need `User=alfresco` but we also need to add `WorkingDirectory=/opt/alfresco/logs` in the same `[Service]` section. Just make sure the `logs` dir exists and is owned by the alfresco user. This is what I believe works now. It may change as I discover more.

**Comment by cuspycode** [comment]
I added `WorkingDirectory` and made some tweaks to your version above @housni. The following works for me on Ubuntu 16.04.1 with the current `alfinstall.sh` script:
```text
# Copy to /etc/systemd/system/alfresco.service
# Then:
#     sudo systemctl enable alfresco.service
#     sudo systemctl daemon-reload
#     sudo systemctl restart alfresco.service

[Unit]
Description=Start Alfresco Community 5 service

[Service]
Type=forking
Environment=LC_ALL=en_US.UTF8
Environment="JAVA_OPTS=-Djava.security.egd=file:/dev/urandom -Xmx2g"
ExecStart=/opt/alfresco/tomcat/bin/startup.sh
ExecStop=/opt/alfresco/tomcat/bin/shutdown.sh
Restart=always
User=alfresco
WorkingDirectory=/opt/alfresco/logs
LimitNOFILE=8192:65536

[Install]
WantedBy=multi-user.target
```
I think it's a matter of taste whether to run `startup.sh/shutdown.sh`, or to run `catalina.sh start/stop`. Systemd will require an extra shell to run the `catalina.sh` script in either case, since systemd doesn't support exec arguments (which are required for the `catalina.sh start/stop` option).

Systemd also doesn't support the incremental building of environment variable values, so having lots of things in JAVA_OPTS will be awkward. Tomcat has a hook for setting environment variables, `$CATALINA_HOME/bin/setenv.sh`, which if it exists is sourced by `catalina.sh`. Maybe that's where JAVA_OPTS should be built? It could source any other file if that makes configuration easier, for example `/home/alfresco/env.sh` or maybe `/etc/default/alfresco`.

Regarding my choice of security.egd, it's perhaps off topic here, but it's my takeaway from [this investigation](https://gist.github.com/svrc/5a8accc57219b9548fe1). It uses /dev/random in Java 7, and /dev/urandom in Java 8, and avoids the closed-source SHA1PRNG in both cases.

**Comment by loftux** [comment]
Closing this as I have pushed a solution to master.
