### ISSUE TITLE
SSO support in reverse proxy

### ISSUE THREAD

**Issue by GusevVictor** [loftuxab/alfresco-ubuntu-install#26]
Hi all. 

Is it possible to use SSO when use nginx as a reverse proxy with alfresco?

I partly use the project for reverse proxy, it works, but SSO - not working...

I'll glad if you read this link: https://forums.alfresco.com/forum/installation-upgrades-configuration-integration/authentication-ldap-sso/sso-doesnt-work

**Comment by loftux** [comment]
Closing this as it has not been reported as an issue further. If nginx does not meet the needs, Apache and mod_jk can be installed and used separately.

**Comment by hi-ko** [comment]
Just a site note: we went back from apache to nginx because it scales much better (incl. caching). To solve the WebDAV issue we compiled our own nginx version having dav proxy support which is not included by default. I will put config & howtos into https://github.com/ecm4u/alfresco-reverse-proxy in the next days
