### ISSUE TITLE
Undocumented requirement for 64 bit jvm

### ISSUE THREAD

**Issue by chris001** [loftuxab/alfresco-ubuntu-install#43]
Peter, First thanks for this install script.

On 32 bit Ubuntu 14.04, ran the script, it uses apt-get to install the matching (32 bit) openjdk 7 JVM from the standard ubuntu 14.04 repo, however it seems to have an undocumented requirement for 64 bit JVM.
Alfresco fails to start.
It sits forever in the browser at the nginx "Alfresco down for maintenance" page.

script~# sudo service alfresco start
alfresco start/running, process 419
~# tail /var/log/upstart/alfresco.log
Error: This Java instance does not support a 64-bit JVM.
Please install the desired version.
~#

**Comment by loftux** [comment]
You just cannot run Alfresco properly on a 32bit system. This is because Java cannot address enough memory on a 32bit system. If you still want to try you can try removing -d64 in /etc/init/alfresco.conf line 42. It may work for a testing environment, but for any production server go with 64 bit and lots of memory.
