### ISSUE TITLE
Add script to OCR the pages of any PDF that has no text layer

### ISSUE THREAD

**Issue by chris001** [loftuxab/alfresco-ubuntu-install#71]
Add tesseract-ocr, leptonica, ephesoft, pdfkit, pdftk, hocr2pdf, pdfjoin, cron job, for automatic OCR on a cron job schedule, to OCR all PDF documents that contain TIFF image and no text layer.

This creates a searchable PDFs from scanned documents, screenshots, images, etc.

https://www.appnovation.com/blog/creating-searchable-pdf-alfresco

https://www.surevine.com/a-little-alfresco-tesseract-ocr-integration/

https://tpeelen.wordpress.com/2010/12/17/alfresco-using-tesseract-ocr-on-ubuntu-linux/

**Comment by loftux** [comment]
Thanks for the suggestion.
We would however try to keep the installer as simple as possible and not having to step through to many options in order to complete an install.

Instead of adding it to the core script, you can create an additional "SetupAddons.sh" script that you can run to add additional features. I'll add it when I get a pull request.
