### ISSUE TITLE
LibreOffice failing to start on Ubuntu 16.04

### ISSUE THREAD

**Issue by douglascrp** [loftuxab/alfresco-ubuntu-install#93]
@loftux I remember we talked about this problem another day, and you told me you got LibreOffice working after executing the startup script at least once.

Today, when I used the restart parameter with the alfresco-service.sh script, I got the following warning messages:

```
/opt/alfresco# Warning: -accept=socket,host=127.0.0.1,port=8100;urp;StarOffice.ServiceManager is deprecated.  Use --accept=socket,host=127.0.0.1,port=8100;urp;StarOffice.ServiceManager instead.
Warning: -headless is deprecated.  Use --headless instead.
Warning: -nofirststartwizard is deprecated.  Use --nofirststartwizard instead.
Warning: -nologo is deprecated.  Use --nologo instead.
Warning: -norestore is deprecated.  Use --norestore instead.
```

I guess that is not a problem with the setup itself, but with the way Alfresco creates the startup command line.

Can you confirm that?
Do you think we should investigate the problem?

**Comment by loftux** [comment]
It is this code that creates the startup parameters
https://github.com/loftuxab/alfresco-community-loftux/blob/loftux/projects/repository/source/java/org/alfresco/util/OpenOfficeCommandLine.java
and this to check the version
https://github.com/loftuxab/alfresco-community-loftux/blob/loftux/projects/repository/source/java/org/alfresco/util/OpenOfficeVariant.java#L118

Doesn't look like very reliable code to determine version...
Maybe I'll change so that it defaults to the double dash command line versions instead, more likely the case moving forward.

**Comment by loftux** [comment]
Updating the version check code for Loftux build now. Since even Alfresco default now ships LIbreoffice > 4, then this pretty much always should use the double dash syntax.

**Comment by douglascrp** [comment]
@loftux Really nice.
Have you raised an issue for that?

**Comment by loftux** [comment]
Filed an issue https://issues.alfresco.com/jira/browse/ALF-21863
